#ifndef RP2350_FAKE_NETINET_TCP_H
#define RP2350_FAKE_NETINET_TCP_H

#define TCP_NODELAY 1
#define TCP_KEEPIDLE 4
#define TCP_KEEPINTVL 5
#define TCP_KEEPCNT 6

#endif /* RP2350_FAKE_NETINET_TCP_H */
